set nocompatible
set backspace=indent,eol,start
set history=50
set ruler
set nobackup
set ignorecase    " Ignore case on searches
set smartcase     " Ignore smartcase if mixed case search
set incsearch     " Search as characters are entered
set hlsearch      " Highlight matches
set showcmd       " Show command in bottom bar
set cmdheight=2   " Set command bar hight to 2
set tabstop=4     " Tab size
set softtabstop=4 " Spaces in tab when editing
set shiftwidth=4  " > Shifts 4 spaces
set expandtab     " Convert tabs to spaces
set smarttab
set modeline
set lazyredraw    " Minimize redraws
set showmatch     " Highlight matching [{()}]
set cursorline    " Highlight/underline current line
"set number       " Show line numbers on left
"set wildmenu     " Visual autocomplete command menu
"set wildmode=longest,full  " Nicer autocompletion
"set list         " Show tabs and spaces at the end of the line
"set listchars=tab:>-,trail:.,extends:>,precedes:<,nbsp:_
"set autoread     " Automatically reload files when changed on disk
"if has("linebreak")
"    let &sbr = nr2char(8168).' '
"endif

if &t_Co > 2 || has("gui_running")
    syntax on
    set hlsearch
endif

if has("gui_running")
    set background=light
else
    set background=dark
endif


"colorscheme solarized


" Only do this part when complied with support for autocommands.
if has("autocmd")
    augroup freebsd
    autocmd!
    if $PORTSDIR != ""
        autocmd BufNewFile $PORTSDIR/*/*/Makefile 0r $PORTSDIR/Templates/Makefile
    else
        autocmd BufNewFile /usr/ports/*/*/Makefile 0r /usr/ports/Templates/Makefile
    endif
    augroup END

    " Enable file type detection.
    " Use the default filetype settings, so that mail gets 'tw' set to 72,
    " 'cindent' is on in C files, etc.
    " Also load indent files, to automatically do language-dependent indenting.
    filetype plugin indent on

    " Put these in an autocmd group, so that we can delete them easily.
    augroup vimrcEx
    au!

    " For all text files set 'textwidth' to 78 characters.
    autocmd FileType text setlocal textwidth=78

    " For git commit message, run it through spell
    autocmd Filetype gitcommit setlocal spell textwidth=72
    
    " For mercurial
    autocmd BufNewFile,BufRead hg-editor-*.txt setf hgcommit spell set tw=72 cc=51,+1

    " When editing a file, always jump to the last known cursor position.
    " Don't do it when the position is invalid or when inside an event handler
    " (happens when dropping a file on gvim).
    autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal g`\"" |
      \ endif

    augroup END

else
    set autoindent                " always set autoindenting on
endif " has("autocmd")

" allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
    set fileencodings=ucs-bom,utf-8,latin1
endif

let g:is_posix = 1

" Point runtimepath to include /usr/local/etc/vim/after
let &rtp=&rtp.',/usr/local/etc/vim/after'

